name: Test

on: push

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install node packages
        run: npm install

      - name: Unit test
        run: npm run test

      - name: UI test
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:3000
